"""migrate_user_to_multi_provider

Revision ID: 614dfea39bc4
Revises: c2a3ee6f4ec9
Create Date: 2026-05-14 07:55:57.251273+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '614dfea39bc4'
down_revision: Union[str, None] = 'c2a3ee6f4ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('users', sa.Column('provider_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_provider_id'), 'users', ['provider_id'], unique=False)
    op.drop_column('users', 'is_social')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_social', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_provider_id'), table_name='users')
    op.drop_column('users', 'provider_id')
    op.drop_column('users', 'provider')
    # ### end Alembic commands ###
